[package]
name = "kwui"
version = "0.1.1"
edition = "2021"
description = "A GUI library with JSX/CSS support"
# publish = ["crates-io"]
license = "LGPL-3.0-or-later"
keywords = ["graphics", "gui", "widgets", "jsx", "quickjs"]
categories = ["gui", "api-bindings"]
repository = "https://gitee.com/wanghoi/kwui-rs"
readme = "README.md"

[lib]
name = "kwui"
path = "src/lib.rs"

[dependencies]
log = "0.4.20"

[dependencies.kwui-sys]
path = "kwui-sys"
version = "0.1.1"

[[example]]
name = "rss_reader"

[[example]]
name = "installer"

[dev-dependencies]
anyhow = "1.0.80"
reqwest = "0.11.24"
rss = "2.0.7"
tokio = { version = "1.36.0", features = ["full"] }
windows_dpi = "0.3.0"

[build-dependencies]
embed-resource = "2.4.1"
