[package]
name = "kwui-macros"
version = "0.1.1"
edition = "2021"
publish = ["crates-io"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = { version = "2.0.60", features = ["full"] }
