/* automatically generated by rust-bindgen 0.69.4 */

pub type kwui_LogCallback =
    ::std::option::Option<unsafe extern "C" fn(msg: *const ::std::os::raw::c_char)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kwui_Application {
    _unused: [u8; 0],
}
extern "C" {
    pub fn kwui_Application_new(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> *mut kwui_Application;
}
extern "C" {
    pub fn kwui_Application_delete(app: *mut kwui_Application);
}
extern "C" {
    pub fn kwui_Application_setLogCallback(callback: kwui_LogCallback);
}
extern "C" {
    pub fn kwui_Application_scriptReloadEnabled() -> bool;
}
extern "C" {
    pub fn kwui_Application_enableScriptReload(enable: bool);
}
extern "C" {
    pub fn kwui_Application_isMainThread() -> bool;
}
extern "C" {
    pub fn kwui_Application_runInMainThread(
        task: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
        udata: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn kwui_Application_setResourceRootDir(
        app: *mut kwui_Application,
        dir: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn kwui_Application_setResourceRootData(
        app: *mut kwui_Application,
        data: *const u8,
        size: usize,
    );
}
extern "C" {
    pub fn kwui_Application_exec(app: *mut kwui_Application) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kwui_Application_quit();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kwui_ScriptValue {
    _unused: [u8; 0],
}
extern "C" {
    pub fn kwui_ScriptValue_newNull() -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_newBool(val: bool) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_newInt(val: ::std::os::raw::c_int) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_newDouble(val: f64) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_newString(
        s: *const ::std::os::raw::c_char,
        len: usize,
    ) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_newArray() -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_newObject() -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_delete(v: *mut kwui_ScriptValue);
}
extern "C" {
    pub fn kwui_ScriptValue_get_by_index(
        arr: *mut kwui_ScriptValue,
        index: ::std::os::raw::c_int,
    ) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_set_by_index(
        arr: *mut kwui_ScriptValue,
        index: ::std::os::raw::c_int,
        val: *mut kwui_ScriptValue,
    );
}
extern "C" {
    pub fn kwui_ScriptValue_get_by_str(
        obj: *mut kwui_ScriptValue,
        key: *const ::std::os::raw::c_char,
    ) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptValue_set_by_str(
        obj: *mut kwui_ScriptValue,
        key: *const ::std::os::raw::c_char,
        val: *mut kwui_ScriptValue,
    );
}
extern "C" {
    pub fn kwui_ScriptValue_is_null(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_is_bool(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_is_number(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_is_string(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_is_array(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_is_object(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_to_bool(v: *mut kwui_ScriptValue) -> bool;
}
extern "C" {
    pub fn kwui_ScriptValue_to_double(v: *mut kwui_ScriptValue) -> f64;
}
extern "C" {
    pub fn kwui_ScriptValue_to_int(v: *mut kwui_ScriptValue) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kwui_ScriptValue_to_string(
        v: *mut kwui_ScriptValue,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn kwui_ScriptValue_length(v: *mut kwui_ScriptValue) -> usize;
}
extern "C" {
    pub fn kwui_ScriptValue_visitArray(
        arr: *mut kwui_ScriptValue,
        visitorFunction: ::std::option::Option<
            unsafe extern "C" fn(
                index: ::std::os::raw::c_int,
                val: *const kwui_ScriptValue,
                udata: *mut ::std::os::raw::c_void,
            ),
        >,
        udata: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn kwui_ScriptValue_visitObject(
        obj: *mut kwui_ScriptValue,
        visitorFunction: ::std::option::Option<
            unsafe extern "C" fn(
                key: *const ::std::os::raw::c_char,
                key_len: usize,
                val: *const kwui_ScriptValue,
                udata: *mut ::std::os::raw::c_void,
            ),
        >,
        udata: *mut ::std::os::raw::c_void,
    );
}
pub type kwui_ScriptFunction = ::std::option::Option<
    unsafe extern "C" fn(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut kwui_ScriptValue,
        udata: *mut ::std::os::raw::c_void,
    ) -> *mut kwui_ScriptValue,
>;
extern "C" {
    pub fn kwui_ScriptEngine_addGlobalFunction(
        name: *const ::std::os::raw::c_char,
        func: kwui_ScriptFunction,
        udata: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn kwui_ScriptEngine_removeGlobalFunction(name: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn kwui_ScriptEngine_loadFile(path: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn kwui_ScriptEngine_callGlobalFunction(
        name: *const ::std::os::raw::c_char,
        argc: ::std::os::raw::c_int,
        argv: *mut *mut kwui_ScriptValue,
    ) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptEngine_postEvent0(event: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn kwui_ScriptEngine_postEvent1(
        event: *const ::std::os::raw::c_char,
        arg: *mut kwui_ScriptValue,
    );
}
extern "C" {
    pub fn kwui_ScriptEngine_sendEvent0(
        event: *const ::std::os::raw::c_char,
    ) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptEngine_sendEvent1(
        event: *const ::std::os::raw::c_char,
        arg: *mut kwui_ScriptValue,
    ) -> *mut kwui_ScriptValue;
}
extern "C" {
    pub fn kwui_ScriptEngine_addEventListener(
        event: *const ::std::os::raw::c_char,
        func: kwui_ScriptFunction,
        udata: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn kwui_ScriptEngine_removeEventListener(
        event: *const ::std::os::raw::c_char,
        func: kwui_ScriptFunction,
        udata: *mut ::std::os::raw::c_void,
    );
}
